version: '3.7'

services:

  db:
    image: mariadb:10
    restart: unless-stopped
    volumes:
      - ./docker-data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_pw
    ports:
      - "3306:3306"


  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root_pw

